services:
  server:
    build:
      context: .
      dockerfile: Server.Dockerfile
    environment:
      GREETING: "Hey there"
    expose:
      - "25250"
  app:
    image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c 'env && sleep infinity'